Pizzaroti/Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PayStack.Net;
using Pizzaroti.Data;
using Pizzaroti.Models;
using System.Net;

namespace Pizzaroti.Controllers
{
    public class PizzaController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly PizzaModelContext _context;
        private readonly string token;
        private PayStackApi PayStack { get; set; }


        public PizzaController(IConfiguration configuration, PizzaModelContext context)
        {
            _configuration = configuration;
            _context = context;
            token = _configuration["Payment:PaystackSK"];
            PayStack = new PayStackApi(token);
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.PizzaModel.ToListAsync());
        }


        //Create Custom Pizza
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

       
        //Create Pizza Post Call//
        [HttpPost]
        public IActionResult Create(PizzasModel pizza)
        {
            float PizzaPrice = pizza.BasePrice;

            if (pizza.TomatoSauce ) PizzaPrice += 500;
            if (pizza.Tuna) PizzaPrice += 500;
            if (pizza.Cheese) PizzaPrice += 500;
            if (pizza.Beef) PizzaPrice += 1000;
            if (pizza.Chicken) PizzaPrice += 1500;
            if (pizza.Ham) PizzaPrice += 500;
            if (pizza.Mushroom) PizzaPrice += 2500;
            if (pizza.Pineapple) PizzaPrice += 3000;
            if (pizza.Peperoni) PizzaPrice += 500;

            return RedirectToAction(nameof(Checkout), new { pizza.PizzaName, PizzaPrice, pizza.ImageTitle });
        }


        //Checkout for Get//
        [HttpGet]
        public IActionResult Checkout(string PizzaName, float PizzaPrice, string ImageTitle)
        {
            if (string.IsNullOrWhiteSpace(PizzaName))
            {
                PizzaName = "Custom";
            }

            if (string.IsNullOrWhiteSpace(ImageTitle))
            {
                ImageTitle = "Create";
            }

            PizzaOrder pizzaOrder = new PizzaOrder();
            pizzaOrder.PizzaName = PizzaName;
            pizzaOrder.PizzaPrice = PizzaPrice;
            pizzaOrder.ImageTitle = ImageTitle;

            _context.PizzaOrders.Add(pizzaOrder);
            _context.SaveChanges();
            return View(pizzaOrder);
        }


        public IActionResult Thankyou()
        {
            return View();
        }



        //Paystack & Checkout Post Call//
        [HttpPost]
        public async Task<IActionResult> Checkout(PizzaOrder order)
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
            TransactionInitializeRequest request = new()
            {
                AmountInKobo = (int)order.PizzaPrice * 100,
                Email = order.Email,
                Reference = Generate().ToString(),
                Currency = "NGN",
                CallbackUrl = "http://localhost:65439/pizza/verify"
            };

            TransactionInitializeResponse response = PayStack.Transactions.Initialize(request);
            if (response.Status)
            {
                var transaction = new TransactionModel()
                {
                    PizzaPrice = (int)order.PizzaPrice,
                    Email = order.Email,
                    PizzaName = order.PizzaName,
                    ImageTitle = order.ImageTitle,
                    TrxRef = request.Reference,
                };
                await _context.Transactions.AddAsync(transaction);
                await _context.SaveChangesAsync();
                return Redirect(response.Data.AuthorizationUrl);
                
            }
            ViewData["error"] = response.Message;
            return View();
        }

        //Payment Get Call//
        [HttpGet]
        public IActionResult Payments()
        {
            var transactions = _context.Transactions.Where(x => x.Status == true).ToList();
            ViewData["transactions"] = transactions;
            return View();
        }

        //Verify Get//
        [HttpGet]
        public async Task<IActionResult> Verify(string reference)
        {
            TransactionVerifyResponse response = PayStack.Transactions.Verify(reference);

            if (response.Data.Status == "success")
            {
                var transaction = _context.Transactions.Where(x => x.TrxRef == reference).FirstOrDefault();
                if(transaction != null)
                {
                    transaction.Status = true;
                    _context.Transactions.Update(transaction);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Thankyou));
                }
            }
            ViewData["error"] = response.Data.GatewayResponse;
            return RedirectToAction(nameof(Checkout));
        }


        public static int Generate()
        {
            Random rand = new Random((int)DateTime.Now.Ticks);
            return rand.Next(10000000, 999999999);
        }
    }
}

Pizzaroti/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizzaroti</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pizzaroti.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ms+Madi&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pizzaroti</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            <span class="visually-hidden">(current)</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Pizza" asp-action="Index">Pizzas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid mainBody">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Pizzaroti
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>